---
title: "Plots for TN STEM Ed Research"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(datavyu)
library(datavyur) # (install via `devtools::install_github("iamamutt/datavyur")`)
library(tidyverse) # install via install.packages("tidyverse")
library(irr) # install via install.packages("irr")
library(here) # install.packages("here")
library(cowplot)  # install via install.packages("cowplot")
```

```{r}
options(directory = here("irr-data", "datavyu_output_01-06-2021_21-30"))
```

Here, I just took the file, column, and codes from above, passing them to `prep_time_series()`. Right now, the code has to include the column; we'll have to change that.
```{r}
prepared_time_series <- prep_time_series(column = "LogClass_AS_ActivityFormat",
                                           code = "code01",
                                         normalize_ts = TRUE) %>% 
  mutate(code = toupper(code))
```

```{r}
attributes(prepared_time_series)$multiple_files <- TRUE

prepared_time_series <- prepared_time_series %>% 
  mutate(file = case_when(
    file == "AW 15-02-26 T602 Content Log" ~ "T602",
    file == "AW and AP Consensus Log T103 14-03-04" ~ "T103",
    file == "AW and AP Consensus T101 14-02-10 Content Log" ~ "T101",
    file == "AW and AP T201 14-12-03 Consensus Log" ~ "T201",
    file == "AW T102 14-02-17 Content Log" ~ "T102"
  ))

prepared_time_series$file <- as.factor(prepared_time_series$file)
levels(prepared_time_series$file) <- c('T101', 'T103', 'T201', 'T102', 'T602')

plot_time_series(prepared_time_series) +
  hrbrthemes::theme_ipsum(base_size = 14) +
  scale_color_brewer(palette = 3, type = "qual") +
  ggtitle("Activity Format")
```

```{r}
ggsave(here("irr-data", "five-teachers-af-3.png"), width = 8, height = 9)
```
