---
title: "Plots for TN STEM Ed Research"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(datavyu)
library(datavyur) # (install via `devtools::install_github("iamamutt/datavyur")`)
library(tidyverse) # install via install.packages("tidyverse")
library(irr) # install via install.packages("irr")
library(here) # install.packages("here")
library(cowplot)  # install via install.packages("cowplot")
```

```{r}
options(directory = here("irr-data", "datavyu_output_11-17-2020_14-11"))
```

```{r}
datavyu_search(here("irr-data", "datavyu_output_11-17-2020_14-11")) %>% 
  distinct(file, column, codes) %>% 
  arrange(column)
```

Here, I just took the file, column, and codes from above, passing them to `prep_time_series()`. Right now, the code has to include the column; we'll have to change that.

```{r}
prepared_time_series_1 <- prep_time_series(column = "LogClass_AS_ActivityFormat",
                                           code = "code01") %>% 
  mutate(code = toupper(code))

prepared_time_series_2 <- prep_time_series(column = "LogClass_AS_ActivityFormat",
                                           code = "code01",
                                           specified_file = "AW T102 14-02-17 Content Log")%>% 
  mutate(code = toupper(code))

prepared_time_series_3 <- prep_time_series(column = "LogClass_AS_ActivityFormat",
                                           code = "code01",
                                           specified_file = "AW and AP Consensus T101 14-02-10 Content Log") %>% 
  mutate(code = toupper(code))

prepared_time_series_4 <- prep_time_series(column = "LogClass_AS_ActivityFormat",
                                           code = "code01",
                                           specified_file = "AW and AP T201 14-12-03 Consensus Log") %>% 
  mutate(code = toupper(code))

prepared_time_series_5 <- prep_time_series(column = "LogClass_AS_ActivityFormat",
                                           code = "code01",
                                           specified_file = "EP 14-03-04 T103 Content Log Consensus")%>% 
  mutate(code = toupper(code))
```

```{r}
p1 <- plot_time_series(prepared_time_series_1) +
  labs(subtitle = NULL) +
  hrbrthemes::theme_ipsum(base_size = 13)+
  xlab(NULL) +
  ggtitle("T602")

p2 <- plot_time_series(prepared_time_series_2) +
  labs(subtitle = NULL) +
  hrbrthemes::theme_ipsum(base_size = 13)+
  xlab(NULL) +
  ggtitle("T102")

p3 <- plot_time_series(prepared_time_series_3) +
  labs(subtitle = NULL) +
  hrbrthemes::theme_ipsum(base_size = 13)+
  xlab(NULL) +
  ggtitle("T101")

p4 <- plot_time_series(prepared_time_series_4) +
  labs(subtitle = NULL) +
  hrbrthemes::theme_ipsum(base_size = 13)+
  xlab(NULL) +
  ggtitle("T201")

p5 <- plot_time_series(prepared_time_series_5) +
  labs(subtitle = NULL) +
  hrbrthemes::theme_ipsum(base_size = 13)+
  xlab(NULL) +
  ggtitle("T103")
```

```{r}
plot_grid(p1, p2, p3, p4, p5, ncol = 2)

ggsave("five-teachers-af.png", width = 10, height = 10)
```
