---
title: "Preparing datavyu Data for Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Preparing-datavyu-Data-for-Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The use of this package requires the use of the *datavyu* software's [Ruby API](https://datavyu.org/user-guide/api.html); note that while *datavyu* has a graphical user interface, it is accompanied by a number of Ruby scripts.

## 1. Download datavyu

datavyu is the qualitative coding software, separate from R/RStudio. It can be downloaded for free here: https://datavyu.org/download.html

## 2. Access and run a Ruby script, datavyu2csv.rb, in datavyu 

Run the following Ruby script (available in this repository) within the datavyu software by selecting Script and then Run Script; select a directory with one or more `.opf` files:

[`datavyu2csv.rb`](https://github.com/tca2/birdseyevyu/blob/master/datavyu2csv.rb)

## 3. Done!

Open the directory that the Ruby script created; a number of CSV files for each `.opf` file should now be created.

This is the directory (folder) passed to the function `options()` when using the {birdseyevyu} R package.
